feat(person): add person
Winzana/sherl-sdk-js pull request #104
Opened 2023-01-25 16:20 UTC by david-chmarzynski

2023-01-26 17:49 UTC, exiam requested changes

2023-01-26 17:49 UTC, exiam commented on src/person/actions/add-person.action.ts
> +export const addPerson = async (
```suggestion
export const createPerson = async (
```

Reprendre les termes du CRUD quand c'est possible.
Renommer les fichiers et autres en conséquence.

2023-01-27 11:27 UTC, exiam commented on src/person/actions/create-person.action.ts
> +): Promise<void> => {
Il me semble que la route de création retourne un objet de type Person. À vérifier et modifier si c'est le cas.

2023-01-27 11:27 UTC, exiam commented on src/person/api/endpoints.ts
> +  POST_CREATE_PERSON: '/api/persons',
```suggestion
  CREATE_PERSON: '/api/persons',
```

2023-01-27 12:09 UTC, david-chmarzynski commented on src/person/actions/create-person.action.ts
> +): Promise<void> => {
Remplacé, data renvoyée dans response.config.data ( JSON parsed )

2023-01-27 14:26 UTC, exiam approved these changes

2023-01-27 14:28 UTC, exiam approved these changes

2023-01-27 14:28 UTC, merged