feat(SHER-710): add actions JSDocs
Winzana/sherl-sdk-js pull request #168
Opened 2023-12-05 10:46 UTC by david-chmarzynski

2023-12-18 16:30 UTC, jg-winzana commented
- Il faudrait raccourcir les JSDoc pour que ce qui est affiché dans l'IDE soit clair sur l'utilisation
- Enlever le paramètre `fetcher`
- Mettre à jour les erreurs qui remontent avec les modifications effectuées ces derniers jours.

2023-12-29 11:56 UTC, exiam requested changes

2023-12-29 11:56 UTC, exiam commented on docs/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
On utilise plutôt npm sur le projet donc le fichier `yarn.lock` n'est pas nécessaire au risque d'entrainer plus de conflits.

2023-12-29 11:56 UTC, exiam commented on src/common/utils/error.ts
> +function filterSherlError(error: unknown, callBackError: unknown): unknown {
À supprimer puisque cette fonction a été remplacée par `getSherlError`

2023-12-29 11:56 UTC, exiam commented on src/organization/provider.ts
> +   * @param {Fetcher} fetcher - The fetcher instance used for making API requests.
À vérifier dans le reste du fichier mais le fetcher ne doit pas être documenté ici.

2023-12-29 11:56 UTC, exiam commented on src/person/actions/get-me.action.ts
> +        throw new Error(`Page not found (status: ${response.status})`);
Il faudrait rebase cette branche avec develop pour récupérer les derniers changements sur la gestion des erreurs

2024-01-02 12:37 UTC, exiam approved these changes

2024-01-02 12:37 UTC, merged