feat(SHER-719): completes errors on analytics domain
Winzana/sherl-sdk-js pull request #179
Opened 2023-12-12 16:45 UTC by jg-winzana

2023-12-13 17:43 UTC, exiam requested changes

2023-12-13 17:43 UTC, exiam commented on src/analytics/actions/get-analytics.action.ts
>        endpoints.ANALYTICS,
Fichier à modifier parce que la route appelée ne retourne pas une liste de `IAnalyticResponse` mais un seul élément. Il s'agit plutôt d'un "find one".

2023-12-13 17:43 UTC, exiam commented on src/analytics/actions/get-audiences-analytics.action.ts
> +      case 404:
Le code 404 n'est pas nécessaire pour cette route de listing.

2023-12-13 17:43 UTC, exiam commented on src/analytics/actions/get-bi-analytics.action.ts
> +      case 404:
Le code 404 n'est pas nécessaire pour cette route de listing.

2023-12-13 17:43 UTC, exiam commented on src/analytics/actions/get-ca-analytics.action.ts
> +      case 404:
Le code 404 n'est pas nécessaire pour cette route de listing.

2023-12-13 17:43 UTC, exiam commented on src/analytics/actions/get-notifications-analytics.action.ts
> +      case 404:
Le code 404 n'est pas nécessaire sur cette route de listing.

2023-12-13 17:43 UTC, exiam commented on src/common/utils/errors.ts
> + * or the callBackError object.
```suggestion
 * or the fallbackError object.
```

2023-12-13 17:43 UTC, exiam commented on src/analytics/actions/get-tracking-analytics.action.ts
> +      case 404:
Pas nécessaire (route de listing)

2023-12-13 17:43 UTC, exiam commented on src/analytics/actions/get-products-analytics.action.ts
> +      case 404:
Pas nécessaire, route de listing

2023-12-14 08:46 UTC, jg-winzana commented on src/analytics/actions/get-analytics.action.ts
>        endpoints.ANALYTICS,
Je viens de vérifier le swagger:
`/api/analytics` Get last order Amount to a person

Le retour est cette interface:
`[
  {
    "id": "string",
    "key": "string",
    "value": 0,
    "number": 0,
    "metadata": {}
  }
]`

Je veux bien la bonne interface du coup si possible.

2023-12-14 11:51 UTC, exiam requested changes

2023-12-14 11:51 UTC, exiam commented on src/analytics/actions/get-bi-analytics.action.ts
>      throw errorFactory.create(AnalyticsErr.ANALYTICS_BI_FAILED);
`getSherlError` à utiliser ici

2023-12-14 11:58 UTC, jg-winzana commented on src/analytics/actions/get-analytics.action.ts
>        endpoints.ANALYTICS,
ITrace est le bon type de retour.

2023-12-14 13:51 UTC, merged