feat(SHER-727): add gallery errors
Winzana/sherl-sdk-js pull request #184
Opened 2023-12-13 10:30 UTC by david-chmarzynski

2023-12-13 10:51 UTC, jg-winzana commented
Sauf erreur de ma part, il manque l'export dans le index.ts du SDK pour Gallery

2023-12-13 12:11 UTC, exiam commented
> Sauf erreur de ma part, il manque l'export dans le index.ts du SDK pour Gallery

@david-chmarzynski à vérifier

2023-12-13 12:16 UTC, exiam requested changes

2023-12-13 12:16 UTC, exiam commented on src/gallery/actions/create-gallery.action.ts
> +      case 404:
Pas besoin de couvrir l'erreur 404 pour cette route POST

2023-12-13 12:16 UTC, exiam commented on src/gallery/actions/delete-dynamic-background.action.ts
> +          GalleryErr.DELETE_DYNAMIC_BACKGROUND_NOT_FOUND,
```suggestion
          GalleryErr.DYNAMIC_BACKGROUND_NOT_FOUND,
```

Pour les codes d'erreurs de type "not found", il pourrait être intéressant de plutôt faire un code d'erreur par ressource. Ici par exemple la ressource concernée est le "DynamicBackground". On aurait donc un seul code d'erreur pour tout ce qui est "DynamicBackground not found" (donc la route DELETE, PUT et GET incluant un ID de DynamicBackground).

2023-12-13 12:16 UTC, exiam commented on src/gallery/actions/delete-dynamic-background.action.ts
> +    throw sherlError;
À mettre sur une seule ligne (j'ai fait des commentaires similaires sur d'autres PR).

2023-12-13 12:16 UTC, exiam commented on src/gallery/actions/delete-gallery.action.ts
> +        throw errorFactory.create(GalleryErr.DELETE_GALLERY_NOT_FOUND);
En suivant mon autre commentaire concernant le code d'erreur, ici on aurait : 

```suggestion
        throw errorFactory.create(GalleryErr.GALLERY_NOT_FOUND);
```

2023-12-13 12:16 UTC, exiam commented on src/gallery/actions/get-dynamic-backgrounds.action.ts
> +      case 404:
Pas besoin de gérer l'erreur 404 sur une route de listing.

2023-12-13 12:16 UTC, exiam commented on src/gallery/actions/get-dynamic-backgrounds.action.ts
> +    throw sherlError;
À mettre sur une seule ligne (pas besoin de la variable intermédiaire `sherlError`).

À appliquer aussi sur les autres fichiers.

2023-12-13 12:16 UTC, exiam commented on src/gallery/actions/get-galleries.action.ts
> +      case 404:
Pas besoin de gérer l'erreur 404 sur une route de listing.

2023-12-13 12:16 UTC, exiam commented on src/gallery/actions/register-dynamic-background.action.ts
> +      case 404:
Pas besoin de gérer l'erreur 404 sur une route de création

2023-12-14 11:46 UTC, exiam requested changes

2023-12-14 11:46 UTC, exiam commented on src/gallery/actions/create-gallery.action.ts
> +      .catch(() => {
Ce catch n'est pas nécessaire étant donné que l'on a déjà le try/catch au dessus.

2023-12-14 11:46 UTC, exiam commented on src/gallery/actions/delete-dynamic-background.action.ts
> +      .catch(() => {
Ce `catch` n'est pas nécessaire comme on a le try/catch au dessus.

2023-12-14 11:46 UTC, exiam commented on src/gallery/actions/delete-gallery.action.ts
> +      .catch(() => {
Ce `catch` n'est pas nécessaire comme on a le try/catch au dessus.

2023-12-14 11:46 UTC, exiam commented on src/gallery/actions/get-dynamic-backgrounds.action.ts
> +      .catch(() => {
Pareil, ce `catch` n'est pas nécessaire comme on a le try/catch au dessus.

2023-12-14 11:46 UTC, exiam commented on src/gallery/actions/get-galleries.action.ts
> +      .catch(() => {
Ce `catch` n'est pas nécessaire comme on a le try/catch au dessus.

À appliquer également dans les autres fichiers.

2023-12-18 12:59 UTC, merged