feat(SHER-728): updates error management
Winzana/sherl-sdk-js pull request #186
Opened 2023-12-13 15:38 UTC by jg-winzana

2023-12-13 17:50 UTC, exiam requested changes

2023-12-13 17:50 UTC, exiam commented on src/iam/actions/get-all-iam-profiles.action.ts
> +      case 404:
Pas nécessaire, il s'agit d'une route de listing.

2023-12-13 17:50 UTC, exiam commented on src/iam/actions/get-iam-profile-by-id.action.ts
> +        throw errorFactory.create(IamErr.IAM_NOT_FOUND_ERROR);
Il faudrait préciser la ressource concernée. La ressource est identifiable en observant l'URL. Ici on récupére un "Profile". Le message d'erreur adapté serait par exemple `IAM_PROFILE_NOT_FOUND`.

2023-12-13 17:50 UTC, exiam commented on src/iam/actions/get-iam-role-by-id.action.ts
> +        throw errorFactory.create(IamErr.IAM_NOT_FOUND_ERROR);
Pareil ici, il faudrait préciser la ressource dans le code d'erreur. Ici la ressource récupérée est un "Role". On pourrait donc avoir `IAM_ROLE_NOT_FOUND`.

2023-12-14 08:01 UTC, jg-winzana commented on src/iam/actions/get-all-iam-profiles.action.ts
> +      case 404:
Ok, listing == 'avec filtre' donc au pire on renvoi un tableau vide

2023-12-14 08:02 UTC, jg-winzana commented on src/iam/actions/get-iam-profile-by-id.action.ts
> +        throw errorFactory.create(IamErr.IAM_NOT_FOUND_ERROR);
Ok j'étais parti sur l'erreur générique.

2023-12-14 08:02 UTC, jg-winzana commented on src/iam/actions/get-iam-role-by-id.action.ts
> +        throw errorFactory.create(IamErr.IAM_NOT_FOUND_ERROR);
OK..

2023-12-14 11:39 UTC, exiam requested changes

2023-12-14 11:39 UTC, exiam commented on src/iam/actions/get-iam-profile-by-id.action.ts
> +        throw errorFactory.create(IamErr.IAM_GET_ALL_FORBIDDEN);
Pour s'en tenir à ce qu'on a fait jusque là, le code d'erreur utilisé pour le 403, à l'inverse de celui qu'on défini pour une 404, doit prendre en compte le nom de la route. Ici ce ne serait donc pas `GET_ALL` mais plutôt `GET_IAM_PROFILE_BY_ID`.

Pareil dans le fichier `src/iam/actions/get-iam-role-by-id.action.ts`.

2023-12-14 16:26 UTC, merged