feat(SHER-726): add error etl  JSDoc
Winzana/sherl-sdk-js pull request #187
Opened 2023-12-13 15:51 UTC by JohanAff

2023-12-15 18:02 UTC, exiam requested changes

2023-12-15 18:02 UTC, exiam commented on src/etl/actions/extract-transform-load.action.ts
> +      case 201:
Cette route retourne un code 200 en cas de succès.

2023-12-18 12:52 UTC, exiam requested changes

2023-12-18 12:52 UTC, exiam commented on src/etl/errors.ts
> +  ETL_NOT_FOUND = 'etl/not_found',
Est-ce que ce code d'erreur est encore utilisé ? si ce n'est pas le cas il faudrait le supprimer.

2023-12-19 09:56 UTC, vinzcoco requested changes
Revois le nommage

2023-12-19 09:56 UTC, vinzcoco commented on src/etl/actions/extract-transform-load-by-id.action.ts
> +        throw errorFactory.create(EtlErr.EXTRACT_TRANSFORM_FORBIDDEN);
Changes par FORBIDDEN

2023-12-19 09:56 UTC, vinzcoco commented on src/etl/actions/extract-transform-load-by-id.action.ts
> +        throw errorFactory.create(EtlErr.EXTRACT_TRANSFORM_LOAD_FAILED);
Change par FAILED

2023-12-19 09:56 UTC, vinzcoco commented on src/etl/actions/extract-transform-load-by-id.action.ts
> +      errorFactory.create(EtlErr.EXTRACT_TRANSFORM_LOAD_FAILED),
Change par FAILED

2023-12-19 09:56 UTC, vinzcoco commented on src/etl/actions/extract-transform-load.action.ts
> +        throw errorFactory.create(EtlErr.EXTRACT_TRANSFORM_LOAD_FORBIDDEN);
Change par FORBIDDEN

2023-12-19 09:56 UTC, vinzcoco commented on src/etl/actions/extract-transform-load.action.ts
> +        throw errorFactory.create(EtlErr.EXTRACT_TRANSFORM_LOAD_FAILED);
Change par FAILED

2023-12-19 09:56 UTC, vinzcoco commented on src/etl/actions/extract-transform-load.action.ts
> +      errorFactory.create(EtlErr.EXTRACT_TRANSFORM_LOAD_FAILED),
Change par FAILED

2023-12-19 10:06 UTC, JohanAff commented on src/etl/actions/extract-transform-load-by-id.action.ts
> +        throw errorFactory.create(EtlErr.EXTRACT_TRANSFORM_FORBIDDEN);
je ne comprend pas le retour

2023-12-19 10:06 UTC, JohanAff commented on src/etl/actions/extract-transform-load-by-id.action.ts
> +        throw errorFactory.create(EtlErr.EXTRACT_TRANSFORM_LOAD_FAILED);
je ne comprend pas le retour vu que EXTRACT_TRANSFORM_LOAD_FAILED c'est deja un FAILED

2023-12-19 18:39 UTC, vinzcoco approved these changes

2023-12-19 18:40 UTC, merged