feat(shop): update errors code management
Winzana/sherl-sdk-js pull request #198
Opened 2023-12-20 13:40 UTC by jg-winzana

2023-12-28 12:37 UTC, exiam requested changes

2023-12-28 12:37 UTC, exiam commented on src/shop/actions/advertisement/create-advertisement.action.ts
> +        throw errorFactory.create(AdvertisementErr.CREATION_FAILED_FORBIDDEN);
De manière générale "FORBIDDEN" me parait suffisant dans le message d'erreur. Par exemple "CREATION_FORBIDDEN". Je n'ai pas l'impression que le "FAILED" apporte quelque chose en plus. Qu'en penses-tu ?

2024-01-18 11:52 UTC, exiam requested changes

2024-01-18 11:52 UTC, exiam commented on src/shop/actions/discount/get-discount.action.ts
> +        throw errorFactory.create(DiscountErr.GET_DISCOUNTS_FORBIDDEN);
```suggestion
        throw errorFactory.create(DiscountErr.GET_DISCOUNT_FORBIDDEN);
```

Pas nécessaire de mettre "discount" au pluriel puisqu'on ne récupére qu'une remise ici.

2024-01-18 11:52 UTC, exiam commented on src/shop/actions/product/get-public-product-by-slug.action.ts
> +        throw errorFactory.create(ProductErr.SLUG_PRODUCT_NOT_FOUND);
```suggestion
        throw errorFactory.create(ProductErr.PRODUCT_NOT_FOUND);
```

2024-01-18 14:54 UTC, jg-winzana commented on src/shop/actions/product/get-public-product-by-slug.action.ts
> +        throw errorFactory.create(ProductErr.SLUG_PRODUCT_NOT_FOUND);
Ok, j'ai aussi fait le changement pour les catégories du coup

2024-01-18 17:35 UTC, exiam approved these changes

2024-01-18 17:37 UTC, exiam requested changes
Il faudrait mettre à jour la branche avec develop avant de pouvoir merge

2024-01-21 15:38 UTC, merged