feat(SHER-739): add jsdoc auth
Winzana/sherl-sdk-js pull request #199
Opened 2023-12-20 14:53 UTC by JohanAff

2023-12-20 16:37 UTC, jg-winzana requested changes

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/actions/login-with-apple.action.ts
> + * Log in using Apple authentication.
```suggestion
 * Logs in the user using Apple authentication.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/actions/login-with-code.action.ts
> + * Log in using a code.
```suggestion
 * Logs in the user using a code.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/actions/login-with-facebook.action.ts
> + * Log in using Facebook authentication.
```suggestion
 * Logs in the user using Facebook authentication.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/actions/login-with-google.action.ts
> + * Log in using Google authentication.
```suggestion
 * Logs in the user using Google authentication.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/actions/logout.action.ts
> + * Log out the user.
```suggestion
 * Logs out the user.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/actions/refresh-token.action.ts
> + * Refresh the authentication token.
```suggestion
 * Refreshes the user's access token.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/actions/resend-sms-code.action.ts
> + * Resend an SMS verification code to the provided mobile phone number.
```suggestion
 * Resends an SMS verification code to the given mobile phone number.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/actions/send-sms-code.action.ts
> + * Send an SMS verification code to the provided mobile phone number.
```suggestion
 * Sends an SMS verification code to the given mobile phone number.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/actions/validate-code.action.ts
> + * Validate an SMS code sent to a mobile phone number.
```suggestion
 * Validates the provided SMS code for the given mobile phone number.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/provider.ts
> +   * Refresh the authentication token.
```suggestion
   * Refreshes the user's access token.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/provider.ts
> +   * Log out the user.
```suggestion
   * Logs out the user.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/provider.ts
> +   * Validate an SMS code sent to a mobile phone number.
```suggestion
   * Validates the provided SMS code sent to the given mobile phone number.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/provider.ts
> +   * Send an SMS verification code to the provided mobile phone number.
```suggestion
   * Sends an SMS verification code to the given mobile phone number.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/provider.ts
> +   * Resend an SMS verification code to the provided mobile phone number.
```suggestion
   * Resends an SMS verification code to the given mobile phone number.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/provider.ts
> +   * Log in using a code.
```suggestion
   * Logs in the user using a code.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/provider.ts
> +   * Log in using Facebook authentication.
```suggestion
   * Logs in the user using Facebook authentication.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/provider.ts
> +   * Log in using Apple authentication.
```suggestion
   * Logs in the user using Apple authentication.
```

2023-12-20 16:37 UTC, jg-winzana commented on src/auth/provider.ts
> +   * Log in using Google authentication.
```suggestion
   * Logs in the user using Google authentication.
```

2023-12-22 08:31 UTC, jg-winzana commented
@JohanAff après discussion avec @exiam, nous pouvons laisser comme ça, je vais clore les retours sur le wording.

2023-12-22 08:34 UTC, jg-winzana approved these changes

2023-12-28 11:17 UTC, exiam approved these changes

2023-12-28 11:17 UTC, merged