feat(SHER-751): add jsdoc opinion
Winzana/sherl-sdk-js pull request #200
Opened 2023-12-20 15:52 UTC by JohanAff

2023-12-20 16:28 UTC, jg-winzana requested changes

2023-12-20 16:28 UTC, jg-winzana commented on src/opinion/actions/claim-opinion.actions.ts
> + * Create a claim related to an opinion.
```suggestion
 * Creates a claim related to an opinion.
```

2023-12-20 16:28 UTC, jg-winzana commented on src/opinion/actions/create-opinion.actions.ts
> + * Create an opinion.
```suggestion
 * Creates an opinion.
```

2023-12-20 16:28 UTC, jg-winzana commented on src/opinion/actions/update-opinion.actions.ts
> + * Update the status of an opinion based on the provided ID and updated opinion status.
```suggestion
 * Updates the status of an opinion based on the provided ID and updated opinion status.
```

2023-12-20 16:28 UTC, jg-winzana commented on src/opinion/provider.ts
> +   * Create an opinion.
```suggestion
   * Creates an opinion.
```

2023-12-20 16:28 UTC, jg-winzana commented on src/opinion/provider.ts
> +   * Update the status of an opinion based on the provided ID and updated opinion status.
```suggestion
   * Updates the status of an opinion based on the provided ID and updated opinion status.
```

2023-12-20 16:28 UTC, jg-winzana commented on src/opinion/provider.ts
> +   * Create a claim related to an opinion.
```suggestion
   * Creates a claim related to an opinion.
```

2023-12-22 08:33 UTC, jg-winzana commented
@JohanAff après discussion avec @exiam, nous pouvons laisser comme ça, je vais clore les retours sur le wording.

2023-12-22 08:33 UTC, jg-winzana approved these changes

2023-12-22 11:10 UTC, jg-winzana commented
👍

2023-12-28 11:22 UTC, exiam requested changes

2023-12-28 11:22 UTC, exiam commented on src/opinion/actions/claim-opinion.actions.ts
> +
```suggestion
```

Saut de ligne en trop que l'on pourrait supprimer

2023-12-28 13:13 UTC, merged