feat(SHER-779): fix error domain iam
Winzana/sherl-sdk-js pull request #217
Opened 2024-01-22 15:42 UTC by JohanAff

2024-01-23 15:04 UTC, david-chmarzynski commented on src/iam/actions/get-all-iam-profiles.action.ts
>          throw errorFactory.create(IamErr.IAM_GET_ALL_FORBIDDEN);
Pour unifier avec le reste : GET_ALL_IAM_FORBIDDEN

2024-01-23 15:05 UTC, david-chmarzynski commented on src/iam/actions/get-iam-profile-by-id.action.ts
>          throw errorFactory.create(IamErr.IAM_PROFILE_NOT_FOUND_ERROR);
IAM_PROFILE_NOT_FOUND

2024-01-23 15:05 UTC, david-chmarzynski commented on src/iam/actions/get-iam-profile-by-id.action.ts
> +        throw getSherlError(error, errorFactory.create(IamErr.FETCH_FAILED));
GET_IAM_PROFILE_BY_ID_FAILED

2024-01-23 15:06 UTC, david-chmarzynski commented on src/iam/actions/get-iam-role-by-id.action.ts
>          throw errorFactory.create(IamErr.IAM_GET_ROLE_BY_ID_FORBIDDEN);
GET_IAM_ROLE_BY_ID_FORBIDDEN

2024-01-23 15:06 UTC, david-chmarzynski commented on src/iam/actions/get-iam-role-by-id.action.ts
> +        throw getSherlError(error, errorFactory.create(IamErr.FETCH_FAILED));
GET_IAM_ROLE_BY_ID_FAILED

2024-01-23 15:06 UTC, david-chmarzynski commented on src/iam/actions/get-all-iam-profiles.action.ts
> +        throw getSherlError(error, errorFactory.create(IamErr.FETCH_FAILED));
GET_ALL_IAM_FAILED

2024-01-24 12:10 UTC, jg-winzana requested changes

2024-01-24 12:10 UTC, jg-winzana commented on src/iam/actions/get-all-iam-profiles.action.ts
> +        throw getSherlError(error, errorFactory.create(IamErr.FETCH_FAILED));
il faut enlever les choses génériques tel que FETCH_FAILED

GET_ALL_IAM_FAILED me semble ok

2024-01-24 12:10 UTC, jg-winzana commented on src/iam/actions/get-iam-profile-by-id.action.ts
> +        throw getSherlError(error, errorFactory.create(IamErr.FETCH_FAILED));
il faut enlever les choses génériques tel que FETCH_FAILED

GET_IAM_PROFILE_BY_ID_FAILED ou IAM_GET_PROFILE_BY_ID_FAILED pour être raccrd avec l'erreur 403 me semble ok

2024-01-24 12:10 UTC, jg-winzana commented on src/iam/actions/get-iam-role-by-id.action.ts
> +        throw getSherlError(error, errorFactory.create(IamErr.FETCH_FAILED));
il faut enlever les choses génériques tel que FETCH_FAILED

GET_IAM_ROLE_BY_ID_FAILED ou IAM_GET_ROLE_BY_ID_FAILED pour être raccrd avec l'erreur 403 me semble ok

2024-01-24 12:49 UTC, jg-winzana requested changes

2024-01-24 12:49 UTC, jg-winzana commented on src/iam/actions/get-iam-role-by-id.action.ts
>          throw errorFactory.create(IamErr.IAM_ROLE_NOT_FOUND_ERROR);
```suggestion
        throw errorFactory.create(IamErr.IAM_ROLE_NOT_FOUND);
```

2024-01-24 12:49 UTC, jg-winzana commented on src/iam/errors.ts
>    IAM_ROLE_NOT_FOUND_ERROR = 'iam/fetch-failed-role-not-found',
```suggestion
  IAM_ROLE_NOT_FOUND = 'iam/fetch-failed-role-not-found',
```

2024-01-24 13:09 UTC, jg-winzana approved these changes

2024-01-24 13:10 UTC, merged