feat(SHER-773): fix error domain cms
Winzana/sherl-sdk-js pull request #226
Opened 2024-01-23 09:43 UTC by JohanAff

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/create-faqs-page.action.ts
> +          errorFactory.create(CmsErr.CMS_CREATE_FAQS_FAILED),
CREATE_CMS_FAQS_CMS_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/create-faqs-page.action.ts
>          throw errorFactory.create(CmsErr.CREATE_CMS_FAQS_FAILED_CMS_FORBIDDEN);
CREATE_CMS_FAQS_CMS_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/create-posts-page.action.ts
> +          errorFactory.create(CmsErr.CMS_CREATE_POSTS_FAILED),
CREATE_CMS_POSTS_CMS_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/create-posts-page.action.ts
>          throw errorFactory.create(CmsErr.CREATE_CMS_POSTS_FAILED_CMS_FORBIDDEN);
CREATE_CMS_POSTS_CMS_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/create-static-page.action.ts
>            CmsErr.CREATE_CMS_STATIC_PAGES_FAILED_FORBIDDEN,
CREATE_CMS_STATIC_PAGES_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/create-static-page.action.ts
> +          errorFactory.create(CmsErr.CMS_CREATE_FAILED),
CREATE_CMS_STATIC_PAGES_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/create-stories-page.action.ts
>            CmsErr.CREATE_CMS_STORIES_FAILED_CMS_FORBIDDEN,
CREATE_CMS_STORIES_CMS_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/create-stories-page.action.ts
> +          errorFactory.create(CmsErr.CMS_CREATE_STORIES_FAILED),
CREATE_CMS_STORIES_CMS_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/create-trainings-page.action.ts
>          throw errorFactory.create(CmsErr.CREATE_CMS_TRAINING_FAILED_FORBIDDEN);
CREATE_CMS_TRAINING_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/create-trainings-page.action.ts
> +          errorFactory.create(CmsErr.CMS_CREATE_TRAININGS_FAILED),
CREATE_CMS_TRAINING_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/delete-article-by-id.action.ts
>          throw errorFactory.create(CmsErr.CMS_DELETE_BY_ID_FAILED_CMS_FORBIDDEN);
CMS_DELETE_ARTICLE_BY_ID_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/delete-article-by-id.action.ts
> +          errorFactory.create(CmsErr.CMS_DELETE_BY_ID_FAILED),
CMS_DELETE_ARTICLE_BY_ID_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/delete-media.action.ts
>          throw errorFactory.create(CmsErr.CREATE_CMS_MEDIA_FAILED_CMS_FORBIDDEN);
DELETE_CMS_MEDIA_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/delete-media.action.ts
> +          errorFactory.create(CmsErr.CMS_DELETE_MEDIA_FAILED),
DELETE_CMS_MEDIA_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-article-by-id.action.ts
>          throw errorFactory.create(CmsErr.CMS_GET_BY_ID_FAILED_POST_FORBIDDEN);
CMS_GET_ARTICLE_BY_ID_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-article-by-id.action.ts
> +          errorFactory.create(CmsErr.CMS_GET_BY_ID_FAILED),
CMS_GET_ARTICLE_BY_ID_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-article-by-slug.action.ts
>          throw errorFactory.create(CmsErr.CMS_GET_SLUG_FAILED_ARTICLE_FORBIDDEN);
CMS_GET_ARTICLE_BY_SLUG_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-article-by-slug.action.ts
> +          errorFactory.create(CmsErr.CMS_GET_SLUG_FAILED),
CMS_GET_ARTICLE_BY_SLUG_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-posts.action.ts
>          throw errorFactory.create(CmsErr.CMS_GET_POSTS_FAILED_POSTS_FORBIDDEN);
CMS_GET_POSTS_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-posts.action.ts
> +          errorFactory.create(CmsErr.CMS_GET_POSTS_FAILED),
CMS_GET_POSTS_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-public-article-by-id.action.ts
>            CmsErr.CMS_GET_PUBLIC_FIND_ID_FAILED_POST_FORBIDDEN,
CMS_GET_PUBLIC_ARTICLE_BY_ID_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-public-article-by-id.action.ts
> +          errorFactory.create(CmsErr.CMS_GET_PUBLIC_FIND_ID_FAILED),
CMS_GET_PUBLIC_ARTICLE_BY_ID_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-public-article-by-slug.action.ts
>          throw errorFactory.create(CmsErr.CMS_GET_SLUG_FAILED_ARTICLE_FORBIDDEN);
CMS_GET_PUBLIC_ARTICLE_BY_SLUG_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-public-article-by-slug.action.ts
> +          errorFactory.create(CmsErr.CMS_GET_SLUG_FAILED),
CMS_GET_PUBLIC_ARTICLE_BY_SLUG_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-public-articles.action.ts
>            CmsErr.CMS_GET_PUBLIC_ARTICLES_FAILED_POSTS_FORBIDDEN,
CMS_GET_PUBLIC_ARTICLES_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/get-public-articles.action.ts
> +          errorFactory.create(CmsErr.CMS_GET_PUBLIC_ARTICLES_FAILED),
CMS_GET_PUBLIC_ARTICLES_FAILED

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/update-article-by-id.action.ts
>          throw errorFactory.create(CmsErr.CREATE_CMS_EVENT_FAILED_CMS_FORBIDDEN);
CMS_UPDATE_ARTICLE_BY_ID_FORBIDDEN

2024-01-23 15:36 UTC, david-chmarzynski commented on src/cms/actions/update-article-by-id.action.ts
> +          errorFactory.create(CmsErr.CMS_UPDATE_ARTICLE_BY_ID_FAILED),
CMS_UPDATE_ARTICLE_BY_ID_FAILED

2024-01-24 10:42 UTC, jg-winzana requested changes

2024-01-24 10:42 UTC, jg-winzana commented on src/cms/actions/add-media.action.ts
>          throw errorFactory.create(CmsErr.CREATE_CMS_EVENT_FAILED_CMS_FORBIDDEN);
Nous sommes effectivement plutôt sur un CMS_ADD_MEDIA_FORBIDDEN, il y a dû y avoir un problème de copié/collé

2024-01-24 10:42 UTC, jg-winzana commented on src/cms/actions/create-faqs-page.action.ts
>          throw errorFactory.create(CmsErr.CREATE_CMS_FAQS_FAILED_CMS_FORBIDDEN);
```suggestion
        throw errorFactory.create(CmsErr.CREATE_CMS_FAQS_CMS_FORBIDDEN);
```

2024-01-24 10:42 UTC, jg-winzana commented on src/cms/actions/create-posts-page.action.ts
>          throw errorFactory.create(CmsErr.CREATE_CMS_POSTS_FAILED_CMS_FORBIDDEN);
```suggestion
        throw errorFactory.create(CmsErr.CREATE_CMS_POSTS_CMS_FORBIDDEN);
```

On a enlevé les FAILED dans d'autres domaines, si on peut être cohérent.

2024-01-24 10:42 UTC, jg-winzana commented on src/cms/actions/delete-media.action.ts
>          throw errorFactory.create(CmsErr.ARTICLE_NOT_FOUND);
ON ne devrait pas être sur un MEDIA_NOT_FOUND ?

2024-01-24 13:04 UTC, jg-winzana requested changes

2024-01-24 13:04 UTC, jg-winzana commented on src/cms/actions/add-media.action.ts
> +        throw errorFactory.create(CmsErr.CREATE_CMS_FAQS_CMS_FORBIDDEN);
```suggestion
        throw errorFactory.create(CmsErr.CMS_ADD_MEDIA_FORBIDDEN);
```

2024-01-24 13:04 UTC, jg-winzana commented on src/cms/actions/create-faqs-page.action.ts
> +        throw errorFactory.create(CmsErr.CREATE_CMS_FAQS_CMS_FORBIDDEN);
```suggestion
        throw errorFactory.create(CmsErr.CREATE_FAQS_CMS_FORBIDDEN);
```

2024-01-24 13:36 UTC, jg-winzana requested changes

2024-01-24 13:36 UTC, jg-winzana commented on src/cms/errors.ts
> +  CMS_CREATE_TRAININGS_FAILED_CMS_NOT_EXIST = 'cms-trainings/cms-create-failed-cms-not-exist',
ils sont utilisé ceux là encore ? Normalement on est passé sur des erreur 404 génériques

2024-01-24 13:36 UTC, jg-winzana commented on src/cms/errors.ts
> +  CMS_DELETE_MEDIA_FAILED_MEDIA_NOT_EXIST = 'cms-delete/cms-create-failed-delete-already-exist',
ils sont utilisé ceux là encore ? Normalement on est passé sur des erreur 404 génériques

2024-01-24 13:52 UTC, jg-winzana approved these changes

2024-01-24 13:52 UTC, merged